image: parity/kubetools:helm3
variables:
  KUBE_NAMESPACE:                  "processbot"
  CI_REGISTRY:                     "paritytech"
  DOCKER_TAG:                      "${CI_COMMIT_TAG}"
  GIT_STRATEGY:                    fetch
  GIT_DEPTH:                       3

stages:
  - check
  - test
  - dockerize
  - deploy

cache:
  key:                             '${CI_JOB_NAME}'
    
check:
  stage: check
  image: parity/rust-builder:latest
  interruptible: true
  dependencies: []
  script:
    - cargo fmt --all -- --check

test:
  stage: test
  image: parity/rust-builder:latest
  interruptible: true
  dependencies: []
  script:
    - export ROCKSDB_LIB_DIR="/usr/lib"
    - export ROCKSDB_STATIC=1
    - cargo test --all
  tags:
    - linux-docker

.build_and_push:                   &build_and_push
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
  tags:
    - kubernetes-parity-build
  image: docker:18-git
  services:
    - docker:18-dind
  script:
    - export DOCKER_IMAGE="${CI_REGISTRY}/${KUBE_NAMESPACE}"
    - export DOCKER_IMAGE_FULL_NAME=$DOCKER_IMAGE:$DOCKER_TAG
    - echo "$Docker_Hub_Pass_Parity" | docker login -u "$Docker_Hub_User_Parity" --password-stdin
    - eval "docker build -t" "$DOCKER_IMAGE_FULL_NAME" .
    - docker push "$DOCKER_IMAGE_FULL_NAME"

#### stage:                        dockerize
dockerize-processbot:
  stage: dockerize
  environment:
    name: parity-build
  only:
    - tags
  <<: *build_and_push

#### stage:                        deploy

.deploy-k8s:                   &deploy-k8s
  script:
    - export DOCKER_TAG
    # check syntax
    - for f in kubernetes/processbot/*yaml; do echo $f; cat $f | envsubst | kubectl --dry-run --validate -n processbot apply -f -; done
    # print rendered yaml
    - for f in kubernetes/processbot/*yaml; do echo $f; cat $f | envsubst; echo '---'; done
    # deploy yaml to cluster
    - for f in kubernetes/processbot/*yaml; do cat $f | envsubst | kubectl -n processbot apply -f -; done

deploy-staging:
  stage: deploy
  environment:
    name: staging-cluster-1
  tags:
    - kubernetes-parity-build
  only:
    - master
  <<: *deploy-k8s

deploy-production:
  stage: deploy
  environment:
    name: parity-prod
  tags:
    - kubernetes-parity-build
  only:
    - tags
  <<: *deploy-k8s

