[package]
name = "parity-pingbot"
version = "0.1.0"
authors = ["Joseph Mark <sjeohp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glitch-in-the-matrix = { git = "https://github.com/paritytech/glitch-in-the-matrix" }
futures = "0.1"
tokio-core = "0.1"
failure = "*"
graphql_client = "0.8"
serde = "^1.0"
serde_json = "1.0"
reqwest = "^0.9"
prettytable-rs = "^0.7"
structopt = "^0.3"
dotenv = "^0.15"
envy = "^0.3"
log = "^0.4"
env_logger = "^0.5"
rocksdb = "0.13"
tokio = { version = "0.2", features = ["full"] }
csv = "1.1"
